version: '3.6'

volumes:
  gems-app:

services:
  web:
    tty: true
    stdin_open: true
    build: .
    environment:
      REDIS_URL: 'redis://redis:6379/12'
      DATABASE_URL: postgres://postgres@db
    command: foreman start -f Procfile.dev
    volumes:
      - ./:/usr/src/app
      - gems-app:/usr/local/bundle
    ports:
      - '3000:3000'
      - '3035:3035'
    depends_on:
      - db
      - redis

  db:
    image: postgres

  redis:
    image: redis
    command: redis-server

  sidekiq:
    build: .
    environment:
      REDIS_URL: 'redis://redis:6379/12'
    command: bundle exec sidekiq -C ./config/sidekiq.yml
    volumes:
      - ./:/usr/src/app
      - gems-app:/usr/local/bundle
    depends_on:
      - db
      - redis
